[[http]]
  display_name = "url地址重写"
  sort = 6
  postion = "normal"
  unique_name = "url_rewrite"

  [[http.items]]
    field_type = "textarea"
    field_display = "block"
    field_clear = "none"
    field_placeholder = "格式：^/test_service(.*) $1\n多条请换行"
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "rewrite_rule"
    field_display_name = "URL重写"
    field_required = false
    field_valid_rule = "/^[\\S]+ [\\S]+$/is"

[[http]]
  display_name = "限流中间件"
  sort = 3
  postion = "normal"
  unique_name = "http_flow_limit"

  [[http.items]]
    field_type = "input"
    field_display = "inline"
    field_clear = "left"
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = "0"
    field_unique_name = "service_flow_limit_num"
    field_display_name = "服务整体限流"
    field_required = false
    field_valid_rule = "/^[\\d]+$/"

  [[http.items]]
    field_type = "select"
    field_display = "inline"
    field_clear = "right"
    field_placeholder = ""
    field_option = "0|1|2,秒|分|时"
    field_value = ""
    field_default_value = "0"
    field_unique_name = "service_flow_limit_type"
    field_display_name = "服务整体限流类型"
    field_required = false
    field_valid_rule = ""

  [[http.items]]
    field_type = "input"
    field_display = "inline"
    field_clear = "left"
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = "0"
    field_unique_name = "clientip_flow_limit_num"
    field_display_name = "客户端IP限流"
    field_required = false
    field_valid_rule = "/^[\\d]+$/"

  [[http.items]]
    field_type = "select"
    field_display = "inline"
    field_clear = "right"
    field_placeholder = ""
    field_option = "0|1|2,秒|分|时"
    field_value = ""
    field_default_value = "0"
    field_unique_name = "clientip_flow_limit_type"
    field_display_name = "客户端IP限流类型"
    field_required = false
    field_valid_rule = ""

[[http]]
  display_name = "Header头转换"
  sort = 3
  postion = "normal"
  unique_name = "header_transfer"

  [[http.items]]
    field_type = "textarea"
    field_display = "inline"
    field_clear = "none"
    field_placeholder = "格式：add key value\n两种方式 add(增加)/edit(修改)\n多条请换行"
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "header_transfer_rule"
    field_display_name = "HEADER头转换"
    field_required = false
    field_valid_rule = "/^[\\S]+ [\\S]+ [\\S]+$/is"

[[http]]
  display_name = "白名单"
  sort = 2
  postion = "normal"
  unique_name = "http_whiteblacklist"

  [[http.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = "格式：127.0.0.1，放行的客户端IP"
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "ip_white_list"
    field_display_name = "IP白名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/is"

[[http]]
  display_name = "连接池设置"
  sort = 2
  postion = "normal"
  unique_name = "http_upstream_transport"

  [[http.items]]
    field_type = "input"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "http_upstream_connection_timeout"
    field_display_name = "下游连接超时(s)"
    field_required = false
    field_valid_rule = "/^[\\d]+$/"

  [[http.items]]
    field_type = "input"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "http_upstream_header_timeout"
    field_display_name = "下游响应超时(s)"
    field_required = false
    field_valid_rule = "/^[\\d]+$/"

[[http]]
  display_name = "jwt验证"
  sort = 2
  postion = "auth"
  unique_name = "jwt_auth"

[[http]]
  display_name = "默认后端配置"
  sort = 2
  postion = "loadbalance"
  unique_name = "upstream_config_new"

  [[http.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = "每个规则一行 如：grpc://127.0.0.1:8701 100"
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "upstream_list"
    field_display_name = "下游服务器ip+权重"
    field_required = false
    field_valid_rule = "/^[\\S]+ [\\S]+$/is"
